# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='secondname',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='surname',
        ),
        migrations.AddField(
            model_name='candidate',
            name='entitled',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
