# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20170501_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='entitled',
            new_name='order',
        ),
    ]
